# docker/docker-compose.test.yml
services:
  eureka-server:
    environment:
      SPRING_PROFILES_ACTIVE: test
      EUREKA_HOSTNAME: eureka-server-test
      EUREKA_DASHBOARD_USERNAME: ${EUREKA_DASHBOARD_USERNAME:?EUREKA_DASHBOARD_USERNAME must be set for test}
      EUREKA_DASHBOARD_PASSWORD: ${EUREKA_DASHBOARD_PASSWORD:?EUREKA_DASHBOARD_PASSWORD must be set for test}
